### ISSUE TITLE
Problems with large pdf files

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#49]
I am having problems with the import and display of large pdf files with mayan 1.0 (document size 500-600 pages). While displaying such a document (/documents/67/view/) works in the dev environment with heavy load on the mayan *and* the browser process (taking minutes), in the production environment the same step runs into gateway timeout (uwsgi behind nginx [3]). Importing such a document in production is even worse leaving behind a corrupted document with only 1 page processed, that can't be deleted (Uninitialized document: 'NoneType' object has no attribute 'filename' ).

This all used to work with mayan 0.13, where the display of the document view was rendered (slowly, but it worked;), while in the background a process completed the previews [1]. With mayan 1.0 the application is for minutes under heavy load end when delivering data to the browser, the browser is unresponsive under heavy load as well, until the view is finally rendered. When finally delivering the data to the browser, logging spits out [2]. Could that have to do with jquery? The new transaction management of django 1.6?

Any input and ideas appreciated!

Mathias

[1]
 [pid: 30580|app: 0|req: 709/3842] 192.168.99.13 () {48 vars in 978 bytes} [Wed Sep 24 18:14:17 2014] GET /documents/19/display/preview/multipage/?rotation=0&version=19&page=523&zoom=100 => generated 108280 bytes in 565 msecs (HTTP/1.1 500) 3 headers in 116 bytes (1 switches on core 0)[pid: 30580|app: 0|req: 709/3842] 192.168.99.13 () {48 vars in 978 bytes} [Wed Sep 24 18:14:17 2014] GET /documents/19/display/preview/multipage/?rotation=0&version=19&page=523&zoom=100 => generated 108280 bytes in 565 msecs (HTTP/1.1 500) 3 headers in 116 bytes (1 switches on core 0)

[2]
[24/Sep/2014 18:39:58] "GET /api/v0/documents/documents/65/image/?size=160x120&rotation=0&version=66&page=9&zoom=100 HTTP/1.1" 200 2684
documents.models <24499> [DEBUG] "get_valid_image() image_cache_name: /home/mathiasb/projects/mayan_10/mayan/mayan/media/image_cache/b8a3eeef552dc4d23e8806cb8f14b1fa1fdfb67e81deb02d7d2ddb626d4897e0"
documents.models <24499> [DEBUG] "get_image() file_path: /tmp/e955d5d9268fbcd088066ac568183b68df59f4fbbc53efe0a097cf324d591adf"
[24/Sep/2014 18:39:58] "GET /api/v0/documents/documents/65/image/?size=160x120&rotation=0&version=66&page=9&zoom=100 HTTP/1.1" 200 2684

[3]
Wed Sep 24 18:21:58 2014 - uwsgi_response_writev_headerWed Sep 24 18:21:58 2014 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 287] during GET /documents/19/view/   
IOError: write error                                                                                                                                
[pid: 32090|app: 0|req: 13/28] 192.168.99.13 () {46 vars in 836 bytes} [Wed Sep 24 18:20:53 2014] GET /documents/19/view/ => generated 0 bytes in 64866 msecs (HTTP/1.1 200) 5 headers in 0 bytes (0 switches on core 1)

**Comment by rosarior** [comment]
@mbehrle Now that migrations on Postgres are working again can you test against your test 500-600+ pages docs to check if we can close this one, thanks!

**Comment by mbehrle** [comment]
* Roberto Rosario: " Re: [mayan-edms] Problems with large pdf files
  (#49)" (Tue, 06 Jan 2015 18:18:53 -0800):

> @mbehrle Now that migrations on Postgres are working again can you test
> against your test 500-600+ pages docs to check if we can close this one,
> thanks!

Hi Roberto,

performance and stability have improved tremendously. I tested with the biggest
documents at hand and it is just fun!

This issue can be closed, I will report some minor issues with further testing
separately.

One question nevertheless:
I tested with 5 workers, of which I assigned the following tasks to just one
individual worker: documents, sources, document_indexing. The other tasks were
assigned to the remaining 2 workers.

The behavior of the upload of a document is, that the GUI returns to
active (with the message 'Document uploaded, will be available shortly') after
parsing of the document:

...
ocr.parsers <12492> [DEBUG] "parse() parsing PDF page 24"
ocr.tasks <12492> [INFO] "task_do_ocr() OCR for document: 15 ended"
documents.models <12492> [DEBUG] "new_version() new_version saved"

i.e. when the document is already available and finished.

Is there something wrong in my setup or could the behavior perhaps still be
improved to get the GUI return immediately and let the workers do their stuff
in the background?



-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6

**Comment by rosarior** [comment]
Awesome! :smile: 

The GUI should return immediately, if it doesn't there is something missing with the Celery setup. Make sure you have CELERY_ALWAYS_EAGER = False in your settings/local.py file otherwise the default CELERY_ALWAYS_EAGER = True from the settings/base.py file will be in effect and the tasks will be execute by the same process handling the GUI, which is what you were seeing.

http://celery.readthedocs.org/en/latest/configuration.html#celery-always-eager

You can also check if the workers are the ones in fact processing the tasks by watching their console output.

**Comment by mbehrle** [comment]
* Roberto Rosario: " Re: [mayan-edms] Problems with large pdf files
  (#49)" (Sat, 10 Jan 2015 10:25:25 -0800):

> Awesome! :smile: 
> 
> The GUI should return immediately, if it doesn't there is something missing
> with the Celery setup. Make sure you have CELERY_ALWAYS_EAGER = False in your
> settings/local.py file otherwise the default CELERY_ALWAYS_EAGER = True from
> the settings/base.py file will be in effect and the tasks will be execute by
> the same process handling the GUI, which is what you were seeing.
> 
> http://celery.readthedocs.org/en/latest/configuration.html#celery-always-eager
> 
> You can also check if the workers are the ones in fact processing the tasks
> by watching their console output.

Ok, got it so far, but still not succeeding in getting it all running.

My observations with CELERY_ALWAYS_EAGER = False:

The only task sucessfully running seems to be the 'converter' task. It is very
nice to see the workers playing together (when having two workers for task
'converter' they are switching fine according to the new tasks). 
When trying to upload a new document, the GUI indeed returns at once, but
there is no new document created, no reaction from the side of the workers.

What indeed is strange:
The tasks executed by the workers assigned to queue 'converter' are namely
those of task: documents.tasks.task_get_document_image, while the worker
assigned to queue 'documents' is idle.


I am still digging in the celery docs to learn more about that. My current
setup looks like this:

BROKER_URL = 'amqp://mayan:mayan@obelix:5672/'
CELERY_RESULT_BACKEND = 'amqp://mayan:mayan@obelix:5672/'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ALWAYS_EAGER = False

I am starting the workers like:

celery -A mayan worker -l INFO -n worker1.%h -Ofair -Q \
converter,checkouts,installation

and the process tree is:

  ├─screen,7005
  │   ├─bash,7022
  │   │   └─python,6926 bin/mayan-edms-mbs.py runserver
  │   │       └─python,8000 bin/mayan-edms-mbs.py runserver
  │   │           └─{python},8010
  │   ├─bash,7079
  │   │   └─celery,6851 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A
  mayan worker -l INFO -n worker1.%h -Ofair -Q converter,checkouts,installation
  │   │       ├─celery,6861 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A
  mayan worker -l INFO -n worker1.%h -Ofair -Q converter,checkouts,installation
  │   │       ├─celery,6862 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A
  mayan worker -l INFO -n worker1.%h -Ofair -Q converter,checkouts,installation
  │   │       ├─celery,6863 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A
  mayan worker -l INFO -n worker1.%h -Ofair -Q converter,checkouts,installation
  │   │       └─celery,6864 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A
  mayan worker -l INFO -n worker1.%h -Ofair -Q converter,checkouts,installation
  │   ├─bash,7134 │   │
  └─celery,6867 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker2.%h -Ofair -Q metadata,mailer,registration │   │
  ├─celery,6877 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker2.%h -Ofair -Q metadata,mailer,registration │   │
  ├─celery,6878 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker2.%h -Ofair -Q metadata,mailer,registration │   │
  ├─celery,6879 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker2.%h -Ofair -Q metadata,mailer,registration │   │
  └─celery,6880 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker2.%h -Ofair -Q metadata,mailer,registration │   ├─bash,7472
  │   │   └─celery,6881 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A
  mayan worker -l INFO -n worker3.%h -Ofair -Q documents │   │
  ├─celery,6891 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker3.%h -Ofair -Q documents │   │
  ├─celery,6892 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker3.%h -Ofair -Q documents │   │
  ├─celery,6893 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker3.%h -Ofair -Q documents │   │
  └─celery,6894 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker3.%h -Ofair -Q documents │   ├─bash,7550 │   │
  └─celery,6895 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker4.%h -Ofair -Q document_indexing │   │
  ├─celery,6905 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker4.%h -Ofair -Q document_indexing │   │
  ├─celery,6906 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker4.%h -Ofair -Q document_indexing │   │
  ├─celery,6907 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker4.%h -Ofair -Q document_indexing │   │
  └─celery,6908 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker4.%h -Ofair -Q document_indexing │   ├─bash,7642 │   │
  └─celery,6910 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker5.%h -Ofair -Q sources │   │
  ├─celery,6920 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker5.%h -Ofair -Q sources │   │
  ├─celery,6921 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker5.%h -Ofair -Q sources │   │
  ├─celery,6922 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker5.%h -Ofair -Q sources │   │
  └─celery,6923 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker5.%h -Ofair -Q sources │   ├─bash,28410 │   │
  └─celery,7685 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker6.%h -Ofair -Q converter │   │
  ├─celery,7695 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker6.%h -Ofair -Q converter │   │
  ├─celery,7696 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker6.%h -Ofair -Q converter │   │
  ├─celery,7697 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker6.%h -Ofair -Q converter │   │
  └─celery,7698 /home/mathiasb/.virtualenvs/mayan_10/bin/celery -A mayan worker
  -l INFO -n worker6.%h -Ofair -Q converter



-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6

**Comment by rosarior** [comment]
I think the problem is the queue name, the queue that handles document uploads is called 'uploads' not 'documents'. This is the list of all the queues in Mayan at the moment: checkouts, mailing, uploads, converter, ocr, tools, indexing, metadata

On a side note, I've uploaded a Vagrant file that sets up a clean development test environment (https://github.com/mayan-edms/mayan-edms/blob/development/Vagrantfile)

Instructions to get it running and test mayan with celery and redis are here: https://github.com/mayan-edms/mayan-edms/blob/development/docs/topics/development.rst#setting-up-a-development-version-using-vagrant

**Comment by mbehrle** [comment]
* Roberto Rosario: " Re: [mayan-edms] Problems with large pdf files
  (#49)" (Tue, 13 Jan 2015 00:27:48 -0800):

> I think the problem is the queue name, the queue that handles document
> uploads is called 'uploads' not 'documents'. This is the list of all the
> queues in Mayan at the moment: checkouts, mailing, uploads, converter, ocr,
> tools, indexing, metadata

Oh yeah, of course! Didn't find the correct grep command to search for those
queue names...:(

Now it is working fast as hell. Absolutely great. Gone those 500 errors for
image generation.

At the same time this was a great test to show, that all tasks were finished as
soon as a worker for the queue was available. AFAIS none ot the old jobs were
lost.

> On a side note, I've uploaded a Vagrant file that sets up a clean development
> test environment
> (https://github.com/mayan-edms/mayan-edms/blob/development/Vagrantfile)
> 
> Instructions to get it running and test mayan with celery and redis are here:
> https://github.com/mayan-edms/mayan-edms/blob/development/docs/topics/development.rst#setting-up-a-development-version-using-vagrant

Thanks, will test that in a while.

My schedule now and leaving finally this issue;):

- Testing further the whole application, especially the new features.
  Will document my observations in a set of new issues for comments.
- Checking the upgrade/migration path of my production DB again for
  postgresql (currently working on a new created DB).
- Evtl. contributing to the docs.
- Updating the german translation (BTW: is there an ETA for 1.1, will you
  announce it to call for translations?).

**Comment by rosarior** [comment]
That is great to hear! Leaving this issue behind gives me much comfort! :)

Putting down two wikis: Release cycle and roadmap, let's continue the discussion there.

https://github.com/mayan-edms/mayan-edms/wiki/Roadmap
https://github.com/mayan-edms/mayan-edms/wiki/Release-cycle
